### ISSUE TITLE
Add github.io preview

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#1]
Looks like this is enabled, but can you add it to the repo description so there is an easy link?

- http://opentraffic.io/tangram-viz-experiments/

**Comment by patriciogonzalezvivo** [comment]
sorry I don't follow the question

**Comment by nvkelso** [comment]
On the main repo page you can edit the project description and add a website link, on the line that begins OT2...:

![image](https://cloud.githubusercontent.com/assets/853051/24159089/74424704-0e1b-11e7-847c-9c2e8a311d3a.png)

**Comment by nvkelso** [comment]
Fixed
