### ISSUE TITLE
Query server for dynamic time range

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#10]
Not sure the server supports this now?

Should make use of Dat interface, see #9.

**Comment by patriciogonzalezvivo** [comment]
Here is where the UI hooks up w the request-maker https://github.com/opentraffic/tangram-viz-experiments/blob/gh-pages/index.html#L709-L710

**Comment by nvkelso** [comment]
From @drewda:

Examples of `start_date_time` and `end_date_time` queries: 

- https://github.com/opentraffic/api/blob/dev/py/query.py#L8-L21

**Comment by patriciogonzalezvivo** [comment]
This will be through the UI right?

**Comment by nvkelso** [comment]
Yes

**Comment by nvkelso** [comment]
The code supports this now, wiring up the params to a GUI was completed in a basic way with presets in #9, followup is covered in https://github.com/opentraffic/tangram-viz-experiments/issues/17.
