### ISSUE TITLE
Refill baseman doesn't draw in Chrome

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#21]
But the overlay does draw?! Chrome Version 56.0.2924.87 (64-bit).

Works fine in Safari version 10.0.3 (10602.4.8.0.1).

<img width="1273" alt="screen shot 2017-03-22 at 2 31 31 pm" src="https://cloud.githubusercontent.com/assets/853051/24221617/45cb53e2-0f0c-11e7-9ffd-6c999b5e554c.png">

**Comment by nvkelso** [comment]
Seems to be an order of operations bug. Sometimes it'll load the first time, sometimes not. But if I pan the map around or zoom the basemap _will_ show on the next draw.

**Comment by patriciogonzalezvivo** [comment]
Mmmm.... maybe @bcamper can give us a hand

**Comment by bcamper** [comment]
I haven't been able to repro this yet (I'm on Chrome 57). Any more info on how/when it happens?

**Comment by nvkelso** [comment]
Hmm, I can't repro today. Maybe it was just my shitty wifi from yesterday? Closing for now, will re-open if it happens again.
