### ISSUE TITLE
Overlapping traffic lines should be offset

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#4]
On the road Maria Clara we have 2 features on top of each other – they should instead be pointing opposite directions and offset from each other. Notice how this works on Vicente Cruz "correctly", though maybe there is a difference of `oneway=true` versus `oneway=false` here.

Not sure if this is a Tangram problem or data problem on the server.

/cc @patriciogonzalezvivo @kevinkreiser 

19/14.61743/120.99033

<img width="586" alt="screen shot 2017-03-21 at 5 08 23 pm" src="https://cloud.githubusercontent.com/assets/853051/24176412/11441cd4-0e59-11e7-9d4d-f0c282e7e6e2.png">

<img width="695" alt="screen shot 2017-03-21 at 5 10 41 pm" src="https://cloud.githubusercontent.com/assets/853051/24176485/79ff0d42-0e59-11e7-9a3f-9fcb3d01506d.png">

<img width="204" alt="screen shot 2017-03-21 at 5 11 05 pm" src="https://cloud.githubusercontent.com/assets/853051/24176486/7a10b6e6-0e59-11e7-8960-d053da4e0fe1.png">

**Comment by nvkelso** [comment]
Even better example where the speeds and colors are different:

http://localhost:8000/#20/14.61097/120.98375

<img width="772" alt="screen shot 2017-03-21 at 5 24 11 pm" src="https://cloud.githubusercontent.com/assets/853051/24176760/4d119186-0e5b-11e7-82e3-c1e3d9123228.png">

**Comment by kevinkreiser** [comment]
yes the are going in the same direction because of a bug we had when we gave @patriciogonzalezvivo this data. its since been fixed so all that needs done is to grab the latest.

**Comment by patriciogonzalezvivo** [comment]
@nvkelso I will re-parse the new geometry to add the average speeds today. That should solve that

**Comment by patriciogonzalezvivo** [comment]
i just push a new version of the geometry. @nvkelso Could you double check directions are good?

**Comment by patriciogonzalezvivo** [comment]
![20](https://cloud.githubusercontent.com/assets/346914/24203975/8016b542-0eed-11e7-8d78-b9a9b366761c.png)

**Comment by nvkelso** [comment]
Verified https://github.com/opentraffic/tangram-viz-experiments/commit/d9f93d699091ab36132943614f07faa94fd8f13a.
