### ISSUE TITLE
Road animation is going wrong way

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#5]
At least in Manila! Here is traffic visualization on Refill, and compared to Walkabout which has the road direction arrows. Both for oneway roads and not oneway roads.

https://mapzen.com/products/maps/walkabout/#lat=14.61894&lng=120.98448&z=19

<img width="598" alt="screen shot 2017-03-21 at 5 13 15 pm" src="https://cloud.githubusercontent.com/assets/853051/24176559/ecee3ef4-0e59-11e7-9a66-abd1869c3830.png">

<img width="654" alt="screen shot 2017-03-21 at 5 14 17 pm" src="https://cloud.githubusercontent.com/assets/853051/24176560/ed079912-0e59-11e7-9908-1e4998ec49f2.png">

**Comment by patriciogonzalezvivo** [comment]
So is consistently in the wrong direction? right?

**Comment by patriciogonzalezvivo** [comment]
I flip the direction of all street. Could you re check now?

**Comment by dnesbitt61** [comment]
Will have to be careful when going to visualize other countries in the region - Indonesia, Singapore, Malaysia (and others in that area) drive on the left.

**Comment by patriciogonzalezvivo** [comment]
I add line to flip the directions on geometries with the `feature.drive_on_right` flag. That should take care of that... right?

**Comment by patriciogonzalezvivo** [comment]
![20](https://cloud.githubusercontent.com/assets/346914/24203960/7706b5f6-0eed-11e7-9f3b-424770a989ad.png)

**Comment by nvkelso** [comment]
Verified fix in https://github.com/opentraffic/tangram-viz-experiments/commit/d5d8551c93043d45bc45e8e11ee2ae70b35bc1fc.
