### ISSUE TITLE
Speed and color breaks

### ISSUE THREAD

**Issue by nvkelso** [opentraffic/tangram-viz-experiments#6]
Regarding:

```- Get a table of speed -> color
- Do we want to interpolate the colors? or have hard breaks between them?
- Style the rest of the geometry (highways, primary roads, etc) that we
  don't have in our sample data
```

Let's mock up:

- fast above 100 km / hr
- medium: between 60 and 100 km / hr
- slow: between 30 and 60 km / hr
- stopped: less than 30 km / hr

no color interpolation (just sharp breaks)

**Comment by patriciogonzalezvivo** [comment]
Just to be clear... there is no fast, medium, slow, stopped color... but this ramp.
 
<img width="737" alt="screen shot 2017-03-22 at 2 10 54 pm" src="https://cloud.githubusercontent.com/assets/346914/24213665/9aae7716-0f09-11e7-8ccd-dca398fc2e77.png">

So green will be abouve 100km. Right?

**Comment by nvkelso** [comment]
Yep

**Comment by patriciogonzalezvivo** [comment]
I suggest setting the max to something lower than 100km... nothing pass over 100km and the map looks more like this


<img width="504" alt="screen shot 2017-03-22 at 2 23 23 pm" src="https://cloud.githubusercontent.com/assets/346914/24214179/22d550c8-0f0b-11e7-8e64-0fcf4910146d.png">

**Comment by nvkelso** [comment]
I'm fine with that – 80 kph? What looks good? Then adjust the other breaks
down a bit?

**Comment by patriciogonzalezvivo** [comment]
These feels more correct https://github.com/opentraffic/tangram-viz-experiments/commit/ef59b1d8579feb67010a17b3f31f28c173b3e741

where
normalized_value = (speed/160)*1.5
normalized_value = 0 -> dark_red
normalized_value = 1.-> green

That would be something like 
fast (green) above 80 km / hr
medium: (yellow) between 53.3 and 80 km / hr
slow: (red) between 26.6 and 53.3 km / hr
stopped: (dark red) less than 26.6 km / hr

**Comment by patriciogonzalezvivo** [comment]
I just simplify this a bunch in https://github.com/opentraffic/tangram-viz-experiments/commit/defb1398629a4000b247355819915ea5fd2cb9a6, is more clear to read for the future


Just for the record, speed data is pass between 0-100 and mapped to the ramp texture directly (using nearest filter to make clear cuts)

**Comment by patriciogonzalezvivo** [comment]
**FUTURE NOTE**: In case of want more stops linearly distributed just make a bigger spectrum palette.... this way is easy to edit if you want something that curves

**Comment by nvkelso** [comment]
That's hard to turn into a legend with clean integer values, can the breaks be more exact?

- fast (green) above 80 km / hr
- medium: (yellow) ≥ **50** and < 80 km / hr
slow: (red) between ≥ **25** and < **50** km / hr
stopped: (dark red) M **25** km / hr

**Comment by patriciogonzalezvivo** [comment]
ok... now is 0-25, 25-50, 50-75, 75-100<

**Comment by nvkelso** [comment]
@patriciogonzalezvivo which commit is the change in so I can follow along, please?

**Comment by patriciogonzalezvivo** [comment]
Here https://github.com/opentraffic/tangram-viz-experiments/commit/defb1398629a4000b247355819915ea5fd2cb9a6

**Comment by nvkelso** [comment]
Which vars create the speed breaks? If I want to change to 30 60 90 how would I do that (just hypothetical)?

**Comment by patriciogonzalezvivo** [comment]
So now in the texture are four pixels, to interpolate the speed between 0
and 100km.

For more control with out coding a line, just add more pixels to the
texture. With a texture of 10px by 1px you can presize the color for 10
speed cuts... repeating the same 4 colors will alow you to have a lot of
control where the color change

**Comment by nvkelso** [comment]
That's rad :)

**Comment by patriciogonzalezvivo** [comment]
: )

There is a ramp block on elevation already on tangran blocks
Just saying ; )

Is a very cheap and powerful technique : )

On Mar 22, 2017 5:21 PM, "Nathaniel V. KELSO" <notifications@github.com>
wrote:

That's rad :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opentraffic/tangram-viz-experiments/issues/6#issuecomment-288543773>,
or mute the thread
